#!/bin/bash

pushd .

# let's activate the build virtual environment

source /venv/build/bin/activate

# First fetch wheel and build c extensions

pip wheel \
    --find-links /wheelhouse/wheels \
    --requirement ./requirements.txt \
    --wheel-dir=/wheelhouse/wheels

rm -rf /tmp/impact_python
mkdir -p /tmp/impact_python/build 

python ./setup.py \
    build \
        -b /tmp/impact_python/build/ \
    bdist_wheel \
        -d /wheelhouse/wheels/ \
    egg_info \
        -e /tmp/impact_python

# Now let's make a Dockerfile context
# we can't symlink wheels into the 'source' directory 'docker/impact_python'
# because are not repeatable across machines and hence not supported by Docker.
# Instead, we just make hard copies of everything we need to build a container into a separate
# directory ('/tmp/impact_python'), build the container, and finally, wipe the build dir.

cp pro-Dockerfile /tmp/impact_python/Dockerfile

cp -r /wheelhouse/wheels /tmp/impact_python/.

docker build -t rebase/pro-impact-python /tmp/impact_python

rm -rf /tmp/impact_python

deactivate

popd
